vich_uploader:
    db_driver: orm

    mappings:
        employe_images:
            uri_prefix: /img/employe_images
            upload_destination: '%kernel.project_dir%/public/img/employe_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
